includes:
  - /media/mohammed/Work/FORMED_ML/config_files/base.yml


model:
  name: schnet
  hidden_channels: 256
  num_filters: 128
  num_interactions: 8
  num_gaussians: 100
  cutoff: 6.0
  use_pbc:                  False
  regress_forces:           False
  otf_graph:                True

# *** Important note ***
#   The total number of gpus used for this run was 8.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 64
  eval_batch_size: 64
  num_workers: 16
  lr_initial: 0.0001
  warmup_steps: 2000
  warmup_factor: 0.2
  max_epochs: 100
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  # No. of epochs to train for.
