# Make sure to run without AMP.
includes:
  - /media/mohammed/Work/FORMED_ML/config_files/base.yml

model:
  name: painn
  hidden_channels: 512
  num_layers: 6
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  use_pbc:                  False
  regress_forces:           False
  otf_graph:                True

  scale_file: /media/mohammed/Work/FORMED_ML/config_files/painn/painn_nb6_scaling_factors.pt


optim:
  batch_size: 32
  eval_batch_size: 32
  num_workers: 16
  lr_initial: 0.0002
  warmup_steps: 2000
  warmup_factor: 0.2
  max_epochs: 50
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3